GET http://localhost:3000/snake/user1
###
GET http://localhost:3000/snake/highScores
###
POST http://localhost:3000/snake/user
Content-Type: application/json

{
  "username": "6666",
  "password": "password1",
  "email": "asdawd@gmail.com"
}
