GET http://localhost:3000/snake/user/2134
###
GET http://localhost:3000/snake/highScores
###
POST http://localhost:3000/snake/score
Content-Type: application/json

{
  "username": "2134",
  "score": 100
}
###
POST http://localhost:3000/snake/user
Content-Type: application/json

{
  "username": "2134",
  "password": "password1",
  "email": "1213123@gmail.com"
}
